### ISSUE TITLE
Incompatibility with Debugify

### ISSUE THREAD

**Issue by Bomb787** [Matyrobbrt/OkZoomerForge#2]
Game seems to crash on startup with Debugify installed on 1.18.2 and Forge 40.1.68.

Latest Log: https://pastebin.com/b4n8jS22
Debug Log: https://pastebin.com/rJtcqV03

**Comment by Matyrobbrt** [comment]
This is a startup crash, and any information about it is printed in the launcher log which I would like to see.

**Comment by Bomb787** [comment]
Ah sorry about that, here you go.

https://pastebin.com/tqLQy26U

**Comment by Matyrobbrt** [comment]
> Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.

**Comment by Bomb787** [comment]
That's weird, it seems to load fine for me when logged out.

**Comment by Matyrobbrt** [comment]
Found it
>>> Info: 2022-08-02 16:54:49.6377008: GameCallbacks.cpp(177)] Game/game () Info Exception in thread "main" java.lang.module.ResolutionException: Module debugify contains package com.llamalad7.mixinextras, module okzoomer exports package com.llamalad7.mixinextras to debugify

**Comment by Matyrobbrt** [comment]
That took a while to figure out, but [2.1.1](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer-forge/files/4081277) should finally fix this long-standing issue.

**Comment by unilock** [comment]
@Matyrobbrt Any chance you could backport that fix to 1.18.2 and publish a new CurseForge release? For ease of use more than anything else, really.

EDIT: It's been done :)
