### ISSUE TITLE
okzoomer-forge-1.19.3-2.2.0.jar 1.19.4 Crash on launch

### ISSUE THREAD

**Issue by ForgeTheSteel** [Matyrobbrt/OkZoomerForge#5]
Seem like it only crash on 1.19.4 but on 1.19.3 it's fine. idk if it's only me who having this crash
https://gist.github.com/ForgeTheSteel/ab3d40bffe2e1ff802b9b95814dae2e7

**Comment by ForgeTheSteel** [comment]
seem like txt won't open here a working one, sorry I never used github before.
https://gist.github.com/ForgeTheSteel/ab3d40bffe2e1ff802b9b95814dae2e7

**Comment by Matyrobbrt** [comment]
2.3.0 is on [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/ok-zoomer-forge/files/4510460) awaiting approval.
