### ISSUE TITLE
1.19-2.1.1 it says "This server restricts the mod" im in singleplayer and i checked the config its enabled

### ISSUE THREAD

**Issue by DTech10** [Matyrobbrt/OkZoomerForge#7]
![2023-07-04_18 25 03](https://github.com/MatyrobbrtMods/OkZoomerForge/assets/136813833/d80e89fd-74cb-4be0-bd84-9cc99c8aa988)

**Comment by Matyrobbrt** [comment]
"restricts" doesn't mean prohibit, it simply means that the server config and client config aren't the same, so the sever ones override it.

**Comment by DTech10** [comment]
> "restricts" doesn't mean prohibit, it simply means that the server config and client config aren't the same, so the sever ones override it.

i checked both configs, its on default and the zoom still doesn't work

**Comment by Matyrobbrt** [comment]
Please join the [Discord server](https://discord.gg/vV25kEaWJX) for further assistance

**Comment by DTech10** [comment]
i joined the server
